services:
  farmapatria:
    build: .
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - farma-api
    environment:
      - JWT_PRIVATE_KEY=${JWT_KEY}
      - DB_URL=${DB_URL}

  farma-api:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
