export const permissions = {
  read: 'READ',
  profile: 'PROFILE',
  create: 'CREATE',
  update: 'UPDATE',
  delete: 'DELETE',
  super: 'SUPER',
  ga: 'GA',
  site: 'SITE',
  ocp: 'OCP',
  gh_aj: 'GH_AJ',
  pop_psi: 'POP_PSI',
  tci: 'TCI',
  uri: 'URI',
  power: 'POWER',
};
